### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "Sukhraj Singh",
  "email": "testing@gmail.com",
  "password": "Sukhraj123"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "sukhraj singh",
    "email": "testing@gmail.com",
    "password": "newpassword123"
}

### Logout User

POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer [your_access_token_here]
Cookie: refreshToken=[your_refresh_token_here]

{
}
### Refresh Token
POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json
Authorization: Bearer [your_access_token_here]
Cookie: refreshToken=[your_refresh_token_here]
{
}

### Resend Verification Email
POST http://localhost:3000/api/auth/resend-verification-email
Content-Type: application/json
Authorization: Bearer [your_access_token_here]
{
}
### Verify Email
GET http://localhost:3000/verify-email?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2wzODQ4dDAwMDByMjluNXpmNmltYWciLCJpYXQiOjE3Njg4MzM1MDUsImV4cCI6MTc2ODgzNDQwNX0.xDkVoiAmphPy93c3qiqPseysLsUpQDXcmu3tEn3sOn4


### Create Link
POST http://localhost:3000/api/links
Content-Type: application/json
Authorization: Bearer [your_access_token_here]
{
  "originalLink": "https://www.example.com/some/very/long/url"
}

### Get Link
GET http://localhost:3000/HixDrL5O

### GET  All Links
GET http://localhost:3000/api/links
Authorization: Bearer [your_access_token_here]

### Delete Link
DELETE http://localhost:3000/api/links/6hlbF9dc
Authorization: Bearer [your_access_token_here]
### Update Link
PUT http://localhost:3000/api/links/6hlbF9dc
Authorization: Bearer [your_access_token_here]
Content-Type: application/json

{
  "originalLink": "https://www.updatedexample.com/updated/url"
}
